[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nodejs_20"]

[phases.install]
cmds = ["composer install --no-interaction --prefer-dist --optimize-autoloader"]

[phases.build]
cmds = ["npm install && npm run dev"]

[start]
cmd = "php artisan optimize && php artisan migrate --force && php -S 0.0.0.0:$PORT -t public/"
